service: sosa

app: sosa
org: ralphcrosales

frameworkVersion: '2'

provider:
  name: aws
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

functions:
  app:
    handler: dist/app.handler
    events:
      - http:
          path: /api
          method: ANY
          cors: true
      - http:
          path: /api/{proxy+}
          method: ANY
          cors: true
